### ISSUE TITLE
Installation in Ubuntu 21.04

### ISSUE THREAD

**Issue by RudinaMSubaih** [JuPedSim/jpsvis#129]
I got this error in the compiling step when I tried to build jpsvis on a laptop with Ubuntu 21.04 OS (command: cmake ..):
-- System ........................................ Linux (5.11.0-41-generic, x86_64)
-- Generating  ................................... jpsvis (0.8.3)
-- Found VTK Version: 9.0.1
-- Found QT Version: 5.15.2
CMake Error at CMakeLists.txt:105 (find_package):
  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

  Add the installation prefix of "glm" to CMAKE_PREFIX_PATH or set "glm_DIR"
  to a directory containing one of the above files.  If "glm" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by chraibi** [comment]
The error tells you that `glm` is not found. Did you install it yet?

Can you try to compile a minimal example to check your installation?


*CMakeLists.txt*

```

cmake_minimum_required(VERSION 3.9)

project(Example LANGUAGES CXX)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/mycpp.cpp)

find_package( glm REQUIRED )

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} glm)
```

```

*mycpp.cpp*

#include "glm/glm.hpp"

int main(){
  return 0;
}
```

**Comment by RudinaMSubaih** [comment]
This issue solved. Thank you Mohcine
Another error appeared while compiling jpsvis ```make``` :
```QVTKOpenGLWidget.h not found```
![image](https://user-images.githubusercontent.com/4458692/148955286-811fcf6d-3906-4941-9462-22f4863e49a6.png)

I think in the ```README``` file we need to add  ```libvtk9-qt-dev```  library as a requirement for Ubuntu (my OS is Ubuntu 21.04)
