### ISSUE TITLE
Mac OS X: crash while closing visualisation window

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsvis#26]
In Gitlab by @chraibi on Apr 20, 2015, 15:06 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsvis/issues/26)]

If only a displayed visualisation window shall be closed, JPSvis crashes with the attached error log. Additionally, the "cmd+w" shortcut for this operation does not work. 

[log.rtf](https://cst.version.fz-juelich.de/jupedsim/jpsvishttps://gitlab.version.fz-juelich.de/JuPedSim/jpsvis/uploads/06cb4e69e6a437fc17c345e264a8f342/log.rtf)

However, the full Quit command (cmd+q) works without any crash.

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 08:02

_Original comment by chraibi on 30 Jun 2015, 09:21_

---

Something _very_ annoying happens, when a window pops up reminding that the last time jpsvis crashed and asking if you want to open it or not, but nether buttons react. So it get stuck and you have to restart jpsvis. :-1:

**Comment by Ozaq** [comment]
Fixed.
