### ISSUE TITLE
router.xml

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsvis#39]
In Gitlab by @chraibi on Jan 27, 2016, 08:34 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsvis/issues/39)]

Can we have an option to open additionally to the geometry file also the router file?

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 08:03

_Original comment by Arne on 27 Jan 2016, 10:15_

---

please elaborate - have not looked into Vis yet. You want to optionally display Hlines, read from the router file?

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Dec 17, 2016, 08:03

_Original comment by chraibi on 27 Jan 2016, 10:59_

---

Yes exactly. I can only visualize the additional Hlines if I open a trajectory file. However, sometimes a simulation is not possible. So the solution maybe:
- open a geometry file and a router file (with Hlines)
- link the router file in the geometry file and open the later. 

This or course has a low priority.

**Comment by chraibi** [comment]
In Gitlab by @ArneGraf on Aug 2, 2017, 14:59

assigned to @chraibi and unassigned @ArneGraf

**Comment by Ozaq** [comment]
I think this can be closed since we are currently reworking core parts of jpscore
