### ISSUE TITLE
Online visualisation

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsvis#44]
In Gitlab by @chraibi on Jun 16, 2016, 10:05 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsvis/issues/44)]

Running JPSvis in Online-mode leads to a SegFault when the connection to a client is closed.

Tested on OS X Yosemite (10.10.5) with [demos/scenario_5_ship/bateau_ini2.xml](https://cst.version.fz-juelich.de/jupedsim/jpscore/blob/develop/demos/scenario_5_ship/bateau_ini2.xml) 

Screenshot of the error

![Screen_Shot_2016-06-16_at_10.01.11](https://gitlab.version.fz-juelich.de/JuPedSim/jpsvis/uploads/5c6938b0b9c0fb3c9495a0452ca325a9/Screen_Shot_2016-06-16_at_10.01.11.png)

**Comment by Ozaq** [comment]
Online mode has been removed.
