### ISSUE TITLE
linux bin

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsvis#49]
In Gitlab by @chraibi on Mar 27, 2017, 18:16 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsvis/issues/49)]

The linux [deb-file](https://github.com/JuPedSim/JuPedSim/releases/download/v0.8.1/jpsvis.deb) is not functional. Missing VTK libs.

**Comment by Ozaq** [comment]
We are not providing packages for linux.
