### ISSUE TITLE
self-compiled JPSvis failed to start

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsvis#52]
In Gitlab by @ghost on Oct 19, 2017, 21:18 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsvis/issues/52)]

1.) Checkout JPSvis via git clone   
2.) compile  
3.) ./bin/jpsvis => failed to start "Speicherzugriffsfehler"  

System: VM with Linux Mint (based on Debian) in 64-bit.

**Comment by chraibi** [comment]
In Gitlab by @ghost on Oct 20, 2017, 09:13

```
cd /home/user/Downloads/JuPedSim/jpsvis 
&& /home/user/Downloads/clion-2017.2.1/bin/cmake/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /home/user/Downloads/JuPedSim/jpsvis && make
```

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Feb 8, 2018, 15:17

changed the description

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Feb 8, 2018, 15:19

Could you try to use the system's cmake? Something like that:

```
- cd /home/user/Downloads/JuPedSim/jpsvis
- mkdir build
- cd build
- cmake ..
- make
```

**Comment by Ozaq** [comment]
I will close this since we have reworked the build since back then considerably.
