### ISSUE TITLE
OSX | dmg installation issue

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsvis#67]
In Gitlab by @gjaeger on Mar 29, 2019, 10:06 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsvis/issues/68)]

from slack channel *jpsvis*:

Mac user: Could you please try this [28032019JPSvis.dmg](https://fz-juelich.sciebo.de/s/Rnll814hYHgDmf9?)

Mac user: Could you please try this [29032019-jpsvis.dmg](https://fz-juelich.sciebo.de/s/ynYlgQy7bUVF7uM)

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Mar 29, 2019, 10:07

with ***28032019JPSvis.dmg*** on macOS High Sierra (10.13.6 (17G5019):

![dmg](https://gitlab.version.fz-juelich.de/JuPedSim/jpsvis/uploads/1c76e75ab5743505d770cf19aa11d034/dmg.png)

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Mar 29, 2019, 10:08

with ***29032019-jpsvis.dmg*** on macOS High Sierra (10.13.6 (17G5019):

![dmg](https://gitlab.version.fz-juelich.de/JuPedSim/jpsvis/uploads/4c1d0115fd5f19bf99d42c6c034f8e12/dmg.png)

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Mar 29, 2019, 10:09

**result**: High Sierra and Mojave are not compatible!!

**Comment by chraibi** [comment]
In Gitlab by @chraibi on Mar 29, 2019, 10:11

Thanks, Gregor.

These two dmgs don't work. The locally copied Qt-libs still reference system libs. 

```
Dyld Error Message:
  Library not loaded: /usr/local/Cellar/qt/5.12.2/lib/QtCore.framework/Versions/5/QtCore
  Referenced from: /Applications/jpsvis.app/Contents/libs/QtNetwork
```

High Sierra lacking compatibility, is another problem. But, I guess if we solve the qt-dependencies, we can just make a dmg file from within a high sierra machine. Might be compatible for Mojave.

**Comment by chraibi** [comment]
In Gitlab by @gjaeger on Mar 29, 2019, 10:43

from slack channel *jpsvis*:

- qt dependencies are missing in the dmg file

- It looks for qt 15.12.0 but I only have 15.11.0 on my laptop

- Actually, it should work even if you don't have qt at all. It offers all vtk libs, but somehow qt libs are missing

- look in `jpsvis.app/Contents/libs/`

- A lot of VTK libs, but no qt at all

- I just found it’s an open issue https://github.com/auriamg/macdylibbundler/issues/12

**Comment by Ozaq** [comment]
We have new installers written from scratch by @schroedtert
