### ISSUE TITLE
Documents about how to compile jpsvis on windows 10

### ISSUE THREAD

**Issue by chraibi** [JuPedSim/jpsvis#74]
In Gitlab by @xuqiancheng on Jun 17, 2019, 16:47 [[origin](https://gitlab.version.fz-juelich.de/jupedsim/jpsvis/issues/75)]

[Install_JPSvis_on_Windows_10.pdf](https://gitlab.version.fz-juelich.de/JuPedSim/jpsvis/uploads/85b180e4241eefe75fedc04f2ef7efed/Install_JPSvis_on_Windows_10.pdf)

**Comment by xuqiancheng** [comment]
Recommend to use Qt Creator

**Comment by chraibi** [comment]
Not much, but this should be enough: 
https://www.jupedsim.org/jupedsim_install_on_windows.html
