### ISSUE TITLE
Error in simulating the geo.xml files 

### ISSUE THREAD

**Issue by SiddharthVarshney** [JuPedSim/jpsvis#79]
While testing the project for the visualization I was going through the demos.
The first demo worked well.
But from 2nd demo onwards the while running the trajectory file it was through an error as shown:
![Screenshot from 2020-01-29 17-47-14](https://user-images.githubusercontent.com/32801674/73356636-d0a74a80-42c0-11ea-90e0-7a83a986d416.png)

On clicking the `YES` the visualizing is running with bugs. It's not showing the boundaries
![Screenshot from 2020-01-29 17-48-33](https://user-images.githubusercontent.com/32801674/73356719-fa607180-42c0-11ea-8e9f-7c6e92ef01af.png)

To check the errors I was going through the log file but the log file is empty.

What's the possible cause and fix for this bug?

**Comment by chraibi** [comment]
which demo do you mean?

**Comment by SiddharthVarshney** [comment]
[demo.zip](https://github.com/JuPedSim/jpsvis/files/4130303/demo.zip)
This is the demo I was testing. In repository its `scenario_7_floorfield`

**Comment by chraibi** [comment]
I don't know how you get this trajectory file, but an easy fix would be to change this line in the trajectory file 

```
 <file location= "Kobes_geo.xml"/>
```
(`correct_Kobes_geo.xml` does not exist in your zip-file)

If you are working with [jpscore](https://github.com/JuPedSim/jpscore) to make the simulations, then you should see a result like this:

<img width="974" alt="Screenshot 2020-01-30 10 32 50" src="https://user-images.githubusercontent.com/5772973/73437236-43113c80-434c-11ea-8a00-f4f6df03324d.png">


Probably relates to this [issue](https://github.com/JuPedSim/jpscore/issues/635).

**Comment by SiddharthVarshney** [comment]
Yes, I just check `correct_kobes_geo.xml` was present out of the root of this project directory.
Changing the location name or moving `correct_kobes_geo.xml` to the correct location solved the problem.

**Comment by SiddharthVarshney** [comment]
But one thing I also noticed that I have tested for each demo. It's not making that `results` directory by its own.

**Comment by chraibi** [comment]
This `result` directory is a new feature. See this [PR](https://github.com/JuPedSim/jpscore/pull/649)

**Comment by SiddharthVarshney** [comment]
oh..okay... I should update the repo
