### ISSUE TITLE
View rotation

### ISSUE THREAD

**Issue by anna-braun** [JuPedSim/jpsvis#80]
At the moment it is not really possible to get an exact rotation of the top or to the side view, but for some reasons it might be necessary to rotate the top view for 90°, 180° or 270°, or to have an exact side view. It would be very nice to have this options in the "view menu": 

![View](https://user-images.githubusercontent.com/38530070/74829921-5b082a80-5312-11ea-9938-84213c56908c.png)

**Comment by Ozaq** [comment]
@anna-braun I don't know how relevant this is still for you but there has been an option to rotate the top view by a arbitrary degree for some time. If this addresses your issue I would like to close this.

**Comment by anna-braun** [comment]
> @anna-braun I don't know how relevant this is still for you but there has been an option to rotate the top view by a arbitrary degree for some time. If this addresses your issue I would like to close this.

@Ozaq The option to type the angle in the new version is fine, so this issue can be closed. Thank you :)
