### ISSUE TITLE
Loading of large trajectory files

### ISSUE THREAD

**Issue by JetteSchumann** [JuPedSim/jpsvis#83]
Currently, I'm simulating a scenario with 5k agents and 1.5h simulation time in a large geometry. Thus, the combined trajectory files become quite large (several GB). Often it takes 30 minutes to load the geometry and when sliding in time jpsvis fails/exits. 
My workaround so far: combine a few trajectory files (e.g., for 5 minutes simulation time) generated by jpscore and load one after the other with jpsvis to get an overview of the simulation results. This is very time-consuming and makes recording difficult.

Maybe it would be possible to load the trajectory files in chunks (in groups of trajectory files as they are accessed when sliding between frames)?

**Comment by Ozaq** [comment]
@JetteSchumann please try https://github.com/JuPedSim/jpsvis/suites/4277231913/artifacts/111324091
